import { useCallback, useRef, useState } from 'react';
import { ToastRegion } from '../components/common/Toast';
import { CrlImageViewer } from '../components/crl/CrlImageViewer';
import { BGEditor } from '../components/editor/BGEditor';
import { EditorToolbar } from '../components/editor/EditorToolbar';
import { OriginalDocumentViewer } from '../components/editor/OriginalDocumentViewer';
import { Sidebar } from '../components/sidebar/Sidebar';
import { sampleResponse } from '../data/sampleResponse';
import { useToast } from '../hooks/useToast';
import { revalidateGuarantee } from '../services/bgReviewApi';
import { downloadJson } from '../utils/downloadJson';
import { clearGeneratedHighlights, highlightAllMatches, scrollToFirstHighlight } from '../utils/highlightHtml';
const editorElement = (instance) => instance?.editor ?? null;
export function EditorPage({ initialReview, onBack }) { const startingReview = initialReview || sampleResponse; const [review, setReview] = useState(startingReview); const [sidebarOpen, setSidebarOpen] = useState(true); const [mobileOpen, setMobileOpen] = useState(false); const [imageOpen, setImageOpen] = useState(Boolean(startingReview.crl_image)); const [originalOpen, setOriginalOpen] = useState(false); const [loading, setLoading] = useState(false); const [docxLoading, setDocxLoading] = useState(false); const editorRef = useRef(null); const htmlRef = useRef(startingReview.bgTextHtml); const originalHtmlRef = useRef(startingReview.bgTextHtml); const { toasts, showToast, dismissToast } = useToast();
  const cleanCurrentHtml = useCallback(() => { const root = editorElement(editorRef.current); return clearGeneratedHighlights(root ? root.innerHTML : htmlRef.current); }, []); const handleChange = useCallback((html) => { htmlRef.current = clearGeneratedHighlights(html); }, []); const handleHighlight = useCallback((text) => { setMobileOpen(false); const root = editorElement(editorRef.current); if (!root) return showToast('Editor is still loading', 'error'); const count = highlightAllMatches(root, text); if (!count) return showToast('No matching text found', 'error'); scrollToFirstHighlight(root); showToast(`Highlighted ${count} occurrence${count === 1 ? '' : 's'}`, 'success'); }, [showToast]); const handleClear = useCallback(() => { const root = editorElement(editorRef.current); if (root) clearGeneratedHighlights(root); showToast('Highlights cleared', 'info'); }, [showToast]); const handleDownload = useCallback(() => { downloadJson({ ...review, bgTextHtml: cleanCurrentHtml() }); showToast('Review JSON downloaded', 'success'); }, [cleanCurrentHtml, review, showToast]);
  const handleDocxDownload = useCallback(async () => { setDocxLoading(true); try { const { downloadDocxWithClauseComments } = await import('../utils/downloadDocx'); const count = await downloadDocxWithClauseComments(cleanCurrentHtml(), review.onerous_clauses); showToast(`DOCX downloaded with ${count} alternate-clause comment${count === 1 ? '' : 's'}`, 'success'); } catch (error) { showToast(error instanceof Error ? error.message : 'DOCX download failed', 'error'); } finally { setDocxLoading(false); } }, [cleanCurrentHtml, review.onerous_clauses, showToast]);
  const restoreOriginal = useCallback(() => { const original = originalHtmlRef.current; htmlRef.current = original; if (editorRef.current) editorRef.current.value = original; setReview((current) => ({ ...current, bgTextHtml: original })); setOriginalOpen(false); showToast('Original backend document restored', 'success'); }, [showToast]);
  const handleRevalidate = useCallback(async () => { setLoading(true); showToast('Revalidation started', 'info'); try { const currentHtml = cleanCurrentHtml(); const next = await revalidateGuarantee(currentHtml); const nextHtml = next?.bgTextHtml || currentHtml; setReview((current) => ({ ...current, ...(next || {}), bgTextHtml: nextHtml, processResult: next?.processResult ? { ...current.processResult, ...next.processResult, entities: next.processResult.entities ? { ...current.processResult?.entities, ...next.processResult.entities } : current.processResult?.entities } : current.processResult })); htmlRef.current = nextHtml; if (editorRef.current) editorRef.current.value = nextHtml; showToast('Revalidation completed. Original snapshot is still available.', 'success'); } catch (error) { showToast(error instanceof Error ? error.message : 'Revalidation failed', 'error'); } finally { setLoading(false); } }, [cleanCurrentHtml, showToast]);
  const bgClass = review.processResult?.entities?.bg_class || ''; return <div className="flex min-h-screen bg-slate-100 text-slate-900"><Sidebar entities={review.processResult?.entities || {}} highestClause={bgClass} clauses={review.onerous_clauses || []} onSelect={handleHighlight} open={sidebarOpen} onCollapse={() => setSidebarOpen((value) => !value)} mobileOpen={mobileOpen} onMobileClose={() => setMobileOpen(false)} /><main className="min-w-0 flex-1"><EditorToolbar onClear={handleClear} onDownload={handleDownload} onDownloadDocx={handleDocxDownload} onBack={onBack} onRevalidate={handleRevalidate} onOpenOriginal={() => setOriginalOpen(true)} onOpenSidebar={() => setMobileOpen(true)} onToggleImage={() => setImageOpen((value) => !value)} hasImage={Boolean(review.crl_image)} imageOpen={imageOpen} loading={loading} docxLoading={docxLoading} /><section className="flex items-start gap-4 p-3 sm:p-5"><div className="editor-shell min-w-0 flex-1 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-panel"><div className="flex items-center justify-between border-b border-slate-100 bg-slate-50/70 px-4 py-2"><div className="flex items-center gap-2 text-[11px] font-medium text-slate-500"><span className="h-2 w-2 rounded-full bg-emerald-500" />Live editable document</div><button onClick={() => setOriginalOpen(true)} className="text-[10px] font-bold uppercase tracking-wider text-navy-700 hover:underline">View original snapshot</button></div><BGEditor editorRef={editorRef} value={review.bgTextHtml} onChange={handleChange} /></div><CrlImageViewer image={review.crl_image} open={imageOpen} onClose={() => setImageOpen(false)} /></section></main><OriginalDocumentViewer html={originalHtmlRef.current} open={originalOpen} onClose={() => setOriginalOpen(false)} onRestore={restoreOriginal} /><ToastRegion toasts={toasts} onDismiss={dismissToast} /></div>; }
